### ISSUE TITLE
Licensing and approval:

### ISSUE THREAD

**Issue by bwplotka** [sbueringer/thanos-inspect#1]
Hello, 

Seems like there is PR to port your code into Thanos project itself. As maintainer I have two questions:
- Can you add licensing to this project to ensure we are legally ok with this.
- Can you state what's your opinion on this, do we have you approval or not. (: 

https://github.com/improbable-eng/thanos/pull/604/

**Comment by sbueringer** [comment]
Hi,

I've added a license which hopefully let's you do whatever you want with the source code.

You have my approval, although I would really prefer it If there isn't any source code dependency to this repo. 
It's just a quick & dirty tool so I wasn't really planning to have a stable API. (I should have put the packages in 
an internal package).

So I would prefer that you just copy whatever you need 😀

**Comment by bwplotka** [comment]
Awesome, thanks (:
